### ISSUE TITLE
Support for Guzzle 6?

### ISSUE THREAD

**Issue by benwrigley** [j0k3r/graby#121]
My installation seems to be failing because I have guzzle 6 I think?

```
    - Installation request for j0k3r/graby ^1.10 -> satisfiable by j0k3r/graby[1.10.0].
    - j0k3r/graby 1.10.0 requires guzzlehttp/guzzle ^5.2.0 -> satisfiable by guzzlehttp/guzzle[5.2.0, 5.3.0, 5.3.1, 5.3.x-dev] but these confli
ct with your requirements or minimum-stability.
```

**Comment by j0k3r** [comment]
I think so.
An issue already exists about that https://github.com/j0k3r/graby/issues/107 and a work in progress (without much progress in the recent days) PR https://github.com/j0k3r/graby/pull/112 is taking care on using httplug instead of Guzzle which will enable almost any other http client to be used instead of a fixed Guzzle version.
