### ISSUE TITLE
Can it extract product specifications from webpage ?

### ISSUE THREAD

**Issue by ajay01994** [j0k3r/graby#146]
HI there,
 Nice code for article extraction ,i have  a question as can it extract product specifications fom web page like given in in the this -http://lunadong.com/publication/dexter_vldb.pdf  article .or could you share some thoughts in building it

Thanks

**Comment by j0k3r** [comment]
graby extract text from an url. If that url is a pdf file, it use an [external library](https://github.com/smalot/pdfparser) to extract text from it.
It's hard to extract data from that text, because it is not structured anymore (the text from a pdf doesn't have markup).

I've no idea how you can proceed.
You should better check for pdf extraction information instead of graby to achieve what you want.
