### ISSUE TITLE
why are http_header values whitelisted?

### ISSUE THREAD

**Issue by burkemw3** [j0k3r/graby#176]
user-agent and referrer are the only http_header values that are currently supported. How come?

I am still interested in getting bloomberg.com working (#156, wallabag/wallabag#3697). Based on some tests so far, the robot detector is looking at the headers sent. I want to send more headers for bloomberg, but adding the additional headers (e.g. Accept-Encoding) to custom siteconfig doesn't do anything.

filtered twice, in fact:
- https://github.com/j0k3r/graby/blob/a05bdb80508c3291035f3f02eff5b7e83275282b/src/SiteConfig/ConfigBuilder.php#L348
- https://github.com/j0k3r/graby/blob/a05bdb80508c3291035f3f02eff5b7e83275282b/src/Extractor/HttpClient.php#L121-L125

**Comment by j0k3r** [comment]
Because we add them we when we need them.
I recently added the cookie header https://github.com/j0k3r/graby/pull/165 because we need it for RGPD.
I think adding accept header can be a good alternative to https://github.com/wallabag/wallabag/pull/3751

Feel free to fork and add more headers!
I do not want to allow **ALL** headers if we don't need them. And because I prefer to have test for each of them to be sure they are working.
