### ISSUE TITLE
Add support for `wrap_in`

### ISSUE THREAD

**Issue by Kdecherf** [j0k3r/graby#180]
Some site configs have `wrap_in([string]): [xpath]` directives.

As this directive is not supported by fivefilters (_see https://github.com/fivefilters/ftr-site-config/issues/249#issuecomment-276812827_) there's no documentation to say what it does and how it works. Its name suggests that it instructs the content extractor to wrap elements matching `[xpath]` with `string` tags, e.g.: `wrap_in(figure): //img`.

This directive would let us to wrap `span` quotes with `blockquote` tags like on this page: https://washingtonmonthly.com/magazine/january-february-march-2018/how-to-fix-facebook-before-it-fixes-us/

Should we implement it in Graby?

**Comment by j0k3r** [comment]
Might be an interesting feature.

**Comment by techexo** [comment]
I am wondering if it's not possible to implement something more drastic, and which may be more interesting on the long term: the possibility to transform an element (given an XPath) into another element.

In an ideal case, it could be possible to:
- transform elements selected by `//span[contains(@class, 'epq-pull-quote')]` (to take the example of @Kdecherf) into `blockquote`;
- transform all elements selected by `//p/span` into `strong`, for websites using CSS classes instead of semantically good markups; information which is lost with _readability_ hardcore span stripping;
- transform `//a[@class='dictionnary_link_wathever']` into `span` (then stripped by php-readability) to get rid of conjugation links on LeMonde (alternative to _dissolve_ as explained [here](https://github.com/fivefilters/ftr-site-config/issues/249#issuecomment-276812827));
- transform `//ul/li[div]` into `div` (to take [this example](https://github.com/fivefilters/ftr-site-config/issues/249#issuecomment-276905606)). This one might be trickier to do, actually.

Finally, I think that methods (maybe called functions in PHP? Coming from Python, sorry) able to do that would also allow to manipulate the DOM in an easier way and avoid the use of regular expressions in _php-readability_.

**Comment by techexo** [comment]
I've seen this on SO : https://stackoverflow.com/a/4675664, which allows to delete an element selected by an XPath while keeping its content. It would be an easy answer to the point 3 of my post above.

Renaming a node is a bit more troublesome, because it consists to select everything in that node, create a new element, move everything into the latter, then replacing the first node by the new one. However, as tricky as it could be to implement, the method could then be used for all the examples above.

**Comment by Kdecherf** [comment]
@techexo thanks for your feedback. A way to transform/rename a node could be interesting, I think a separate issue for it would be very welcome ;-)
