### ISSUE TITLE
safecurl has an issue in the latest release (1.1)

### ISSUE THREAD

**Issue by tcitworld** [j0k3r/graby#23]
See https://github.com/fin1te/safecurl/blob/v1.1/src/fin1te/SafeCurl/SafeCurl.php#L151 : `Execption`. The typo is fixed in the master branch. I've sent a tweet and will probably [contact him](https://fin1te.net/about/) by email if necessary.

This causes wallabag to fail dramatically when adding a link with no working connexion.

**Comment by j0k3r** [comment]
I'm aware of this bug ... which is fixed in the master of the SafeCurl repo but I prefer to wait for a new release of safecurl ...

I already sent him a tweet few days ago without answer .. https://twitter.com/j0k/status/644843433446739968

If it take too long, I can still switch to `dev-master` instead of `1.1`.

**Comment by j0k3r** [comment]
@tcitworld did you get any reply from that guy? It seems to ignore any request ... https://github.com/j0k3r/safecurl/pull/1

**Comment by tcitworld** [comment]
I didn't sent him an email yet. I'll do it today.
